services:
 client:
   build:
     context: ./penny-pilot-client
   container_name: penny-pilot-client
   restart: always
   ports:
     - 3000:3000
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost:3001/api
   networks:
     - network

 api:
  build:
    context: ./penny-pilot-api
  container_name: penny-pilot-api
  restart: always
  ports: 
    - 3001:3001
  networks:
    - network

 cassandra:
  image: cassandra:5.0
  container_name: penny-pilot-cassandra
  ports:
    - 3002:3002
    - 9042:9042
    - 9160:9160
  environment:
    - cassandra_user={{ secrets.CASSANDRA_USER}}
    - cassandra_password={{ secrets.CASSANDRA_PASSWORD }}
  volumes:
  - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
   
networks:
 network: