services:
 client:
   build:
     context: ./client
   container_name: penny-pilot-client
   restart: always
   ports:
     - 3000:3000
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost:3001/api
   networks:
     - network

 api:
  build:
    context: ./api
  container_name: penny-pilot-api
  restart: always
  ports: 
    - 3001:3001
  networks:
    - network
   
networks:
 network: