name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Compose Images
        run: docker compose -f docker-compose.yml build
        
      - name: Push image to Container Registry
        run: docker penny-pilot-client push https://ghcr.io/penny-pilot-client:latest

          
