on: [push]

jobs:
  client_hello_world:
    runs-on: ubuntu-latest
    name: Tests a client by running a docker compose
    container: docker
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Builds the docker composed image"
        id: build
        run: docker compose build
