name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Compose Images
        run: docker compose -f docker-compose.yml build
        
      - name: Tag Client
        run: docker tag penny-pilot-client https://ghcr.io/penny-pilot-client:latest

      - name: Tag API
        run: docker tag penny-pilot-api https://ghcr.io/penny-pilot-api:latest

      - name: Push Client
        run: docker push https://ghcr.io/penny-pilot-client:latest

      - name: Push API
        run: docker push https://ghcr.io/penny-pilot-api:latest


          
